// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC755VavkSncCBAWnlSKIaqVGyqY-XCepc',
    appId: '1:216646888379:web:5dfd09f4d8eb5b2bb5f29e',
    messagingSenderId: '216646888379',
    projectId: 'todo-app-3539a',
    authDomain: 'todo-app-3539a.firebaseapp.com',
    storageBucket: 'todo-app-3539a.appspot.com',
    measurementId: 'G-XBV4WSSF48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBX574SLOGrNx5jUAk2LMBSMrj6hx3xFY',
    appId: '1:216646888379:android:e6dc8830451cfd41b5f29e',
    messagingSenderId: '216646888379',
    projectId: 'todo-app-3539a',
    storageBucket: 'todo-app-3539a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHqPily487IC3nkTjSpP0GDiJhsAsI2Uk',
    appId: '1:216646888379:ios:4a6444d7580affbeb5f29e',
    messagingSenderId: '216646888379',
    projectId: 'todo-app-3539a',
    storageBucket: 'todo-app-3539a.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHqPily487IC3nkTjSpP0GDiJhsAsI2Uk',
    appId: '1:216646888379:ios:4a6444d7580affbeb5f29e',
    messagingSenderId: '216646888379',
    projectId: 'todo-app-3539a',
    storageBucket: 'todo-app-3539a.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC755VavkSncCBAWnlSKIaqVGyqY-XCepc',
    appId: '1:216646888379:web:b265f3aa52ea8a3cb5f29e',
    messagingSenderId: '216646888379',
    projectId: 'todo-app-3539a',
    authDomain: 'todo-app-3539a.firebaseapp.com',
    storageBucket: 'todo-app-3539a.appspot.com',
    measurementId: 'G-8CRQD8JQ98',
  );
}
